package com.donationmatch.request.entity;

public enum ItemType {
    CANNED_VEGETABLES,
    CANNED_FRUIT,
    CANNED_MEAT_FISH,
    CANNED_BEANS_LEGUMES,
    PASTA_RICE_GRAINS,
    CEREAL_BREAKFAST,
    BREAD_BAKERY,
    DAIRY,
    FRESH_PRODUCE,
    FROZEN_MEAT_PROTEIN,
    BABY_FOOD_SUPPLIES,
    HYGIENE_PRODUCTS,
    BEVERAGES,
    CONDIMENTS_SAUCES_SPICES,
    OTHER
}
