server:
  port: 8082

spring:
  application:
    name: request-service
  datasource:
    url: jdbc:postgresql://localhost:5432/request_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    # Producer/consumer beans defined in KafkaProducerConfig, KafkaConsumerConfig.
    consumer:
      group-id: request-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
